SELECT CARIGEN.P_ID As Referans,CARIGEN.CRK as CariHesapKodu,CARIGEN.STA as CARIADI,EPOSTA as EPOSTA,VERGINO as VERGINO,
 VW_CARI_AYLIK_BAKIYELER_22.BAKIYE AS BAKIYE,
VW_CARI_AYLIK_BAKIYELER_22.BAKIYE as TUTAR,
isnull(Adet,0) as ADET,GuncelBakiye AS GUNCELBAKIYE,GuncelBakiyeTuru AS GUNCELBAKIYETURU,VW_CARI_AYLIK_BAKIYELER_22.BAKIYETURU as BAKIYETURU, isnull(AylikToplam,0) as AYLIKTOPLAM   FROM 
  (SELECT   CARIKODU,   abs( ROUND(SUM(bAKIYESI),2))     as GuncelBakiye,  
CASE WHEN  ROUND(SUM(bAKIYESI),2)>0 THEN 'B' WHEN  ROUND(SUM(bAKIYESI),2)< 0 THEN 'A' ELSE ' ' END    AS GuncelBakiyeTuru   
  FROM CARIDURUM() where CARIKODU is not null 
GROUP BY CARIKODU 
) TBL 
 LEFT JOIN VW_CARI_AYLIK_BAKIYELER_22 ON     TBL.CARIKODU =  VW_CARI_AYLIK_BAKIYELER_22.CRK AND VW_CARI_AYLIK_BAKIYELER_22.AY = 8
left join (select GMHK,count(GENELTOPLAM) AS Adet,sum(GENELTOPLAM) as AylikToplam from [LISTEFATURA]() t1 where  month(t1.EVRAKTAR) =8 group by GMHK ) t1  
ON TBL.CARIKODU = t1.GMHK
LEFT join CARIGEN ON CARIGEN.CRK = TBL.CARIKODU

where   CARIKODU like '120%' and   CARIKODU not like '%-340' --and CRK LIKE 'AK%'


--SELECT SUM(TUTARB-TUTARA) FROM DBO.CARI_EKSTRE('120.0430367835','20220101','20220630')


select EPOSTA, * from CARIGEN  WHERE CRK = '120.0430367835'

'muhasebe@akyapak.com.tr;mcelikakyapak.com.tr'

UPDATE CARIGEN SET  EPOSTA  = 'serkansonmez16@gmail.com'  WHERE CRK = '120.0430367835'

UPDATE CARIGEN SET  EPOSTA  ='muhasebe@akyapak.com.tr;mcelikakyapak.com.tr' WHERE CRK = '120.0430367835'