set dateformat dmy

declare @TARIH1 datetime,
		@TARIH2 datetime,
		@ISLEMP_ID varchar(200)
declare @mdl varchar(100)

SET @TARIH1 = '01.06.2022'
SET @TARIH2 = '29.06.2022'
set @mdl = ''

DECLARE @ORAN1 FLOAT, @ORAN2 FLOAT, @ORAN3 FLOAT, @ORAN4 FLOAT
	
DECLARE @KDVTOPLAMLARI TABLE (P_ID VARCHAR(80) collate TURKISH_CI_AS,KDVY FLOAT,KDVTL FLOAT,INDTL FLOAT,SATINDTL FLOAT,
							  OTVTL FLOAT,TUTARTL FLOAT)

INSERT INTO @KDVTOPLAMLARI
SELECT FATURA_ALT.P_ID,ISNULL(KDVY,0),SUM(ISNULL(KDVTL,0)),SUM(ISNULL(INDTL,0)),SUM(ISNULL(SATINDTL,0)),
				 SUM(ISNULL(OTVTL,0)),SUM(ISNULL(TUTARTL,0)) 
				 FROM FATURA_ALT 
				 GROUP BY FATURA_ALT.P_ID,ISNULL(FATURA_ALT.KDVY,0)

DECLARE @FATURATOPLAMLARI TABLE (FP_ID VARCHAR(80) collate TURKISH_CI_AS,TUTARTL FLOAT, TUTARD FLOAT,
			TOPLAMTL FLOAT,TOPLAMD FLOAT,
			TOPLAMOTV FLOAT, TOPLAMTVK FLOAT, TOPLAMTVKD FLOAT, TOPLAMIND FLOAT,
			TOPLAMGV FLOAT, TOPLAMFON FLOAT, TOPLAMBAGKUR FLOAT, TOPLAMKESINTI FLOAT,
			TOPLAMOTVODENEN FLOAT, TOPLAMOTVTECIL FLOAT, TOPLAMBORSA FLOAT,
			TOPLAMINDSIZKDV FLOAT, TOPLAMINDTL FLOAT, TOPLAMOIV FLOAT,TOPLAMMERAFONU FLOAT,
			DAHILTOPLAMTL FLOAT, DAHILTOPLAMD FLOAT, TOPLAMOTVD FLOAT, TOPLAMMASRAF FLOAT,
			TOPLAMMASRAFD FLOAT, TOPLAMGVD FLOAT, TOPLAMFOND FLOAT, TOPLAMBAGKURD FLOAT,
			TOPLAMKESINTID FLOAT, NETTOPLAMD FLOAT, TOPLAMOTVODENEND FLOAT, TOPLAMOTVTECILD FLOAT,
			TOPLAMBORSAD FLOAT, TOPLAMOIVD FLOAT, TOPLAMMERAFONUD FLOAT, UGDK FLOAT, DOVIZC INT,
			NETTOPLAM FLOAT, TOPLAMINDD FLOAT,RUSUM_TUTAR FLOAT) 


INSERT INTO @FATURATOPLAMLARI (FP_ID, TUTARTL, TUTARD, TOPLAMTL, TOPLAMD,
			TOPLAMOTV, TOPLAMTVK, TOPLAMTVKD, TOPLAMIND, TOPLAMGV, TOPLAMFON, 
			TOPLAMBAGKUR, TOPLAMKESINTI, TOPLAMOTVODENEN, TOPLAMOTVTECIL, TOPLAMBORSA,
			TOPLAMINDSIZKDV, TOPLAMINDTL, TOPLAMOIV,TOPLAMMERAFONU, DAHILTOPLAMTL, DAHILTOPLAMD,
			TOPLAMMASRAF, NETTOPLAM, TOPLAMINDD,RUSUM_TUTAR)
SELECT P_ID,SUM(ISNULL(TUTARTL,0)), SUM(ISNULL(TUTARD,0)),SUM(ISNULL(TUTARTL,0)),SUM(ISNULL(TUTARD,0)),	
		SUM(ISNULL(OTVTL,0)), SUM(ISNULL(TEVKTL,0)),SUM(ISNULL(TEVKD,0)),SUM(ISNULL(INDTL,0)), 
		SUM(ISNULL(GVSTOPAJTUTARITL,0)),SUM(ISNULL(FONTUTARITL,0)),SUM(ISNULL(BAGKURTUTARTL,0)),
		SUM(ISNULL(KESINTITOPLAMTL,0)),SUM(ISNULL(SOTVODENENTL,0)),SUM(ISNULL(SOTVTECILTL,0)),SUM(ISNULL(BORSATUTARTL,0)),
		SUM(ISNULL(INDSIZKDV,0)),SUM(ISNULL(INDTL,0)), SUM(ISNULL(OIVTUTARTL,0)),
		SUM(ISNULL(MFYTUTARTL,0)),
		SUM(isnull(TMT,0)),			   
		SUM(isnull(DMT,0)),
		SUM(ISNULL(SATMASRAFTL,0)), SUM(ISNULL(NETTUTARTL,0)), SUM(ISNULL(INDD,0)),
		SUM(isnull(RUSUM_TUTAR,0))
			
		FROM FATURA_ALT
		GROUP BY FATURA_ALT.P_ID

UPDATE @FATURATOPLAMLARI SET UGDK = isnull((SELECT isnull(UGDK,0) FROM FATURA WHERE FATURA.P_ID = FP_ID),0),
DOVIZC = isnull((SELECT isnull(DOVIZC,1) FROM FATURA WHERE FATURA.P_ID = FP_ID),1)

UPDATE @FATURATOPLAMLARI SET TOPLAMMASRAFD = TOPLAMMASRAF / UGDK, TOPLAMGVD = TOPLAMGV / UGDK, 
TOPLAMFOND = TOPLAMFON / UGDK, TOPLAMBAGKURD = TOPLAMBAGKUR / UGDK, TOPLAMKESINTID = TOPLAMKESINTI / UGDK, 
NETTOPLAMD = NETTOPLAM / UGDK, TOPLAMOTVODENEND = TOPLAMOTVODENEN / UGDK, 
TOPLAMOTVTECILD = TOPLAMOTVTECIL / UGDK, TOPLAMBORSAD = TOPLAMBORSA / UGDK, 
TOPLAMOIVD = TOPLAMOIV / UGDK, TOPLAMMERAFONUD = TOPLAMMERAFONU / UGDK
WHERE UGDK>0

		 SELECT TOP 1 @ORAN1 = CONVERT(NUMERIC(20,2),CASE WHEN ISNULL(REPLACE(STRINGDEGER,',','.'),'1') = '' THEN 0 
					ELSE ISNULL(REPLACE(STRINGDEGER,',','.'),'1') END) FROM AYARLAR WHERE KULLANICI = 'GENEL' AND COMPADI = 'kdv2'
		 SELECT TOP 1 @ORAN2 = CONVERT(NUMERIC(20,2),CASE WHEN ISNULL(REPLACE(STRINGDEGER,',','.'),'8') = '' THEN 0 
					ELSE ISNULL(REPLACE(STRINGDEGER,',','.'),'8') END) FROM AYARLAR WHERE KULLANICI = 'GENEL' AND COMPADI = 'kdv3'
		 SELECT TOP 1 @ORAN3 = CONVERT(NUMERIC(20,2),CASE WHEN ISNULL(REPLACE(STRINGDEGER,',','.'),'18') = '' THEN 0 
					ELSE ISNULL(REPLACE(STRINGDEGER,',','.'),'18') END) FROM AYARLAR WHERE KULLANICI = 'GENEL' AND COMPADI = 'kdv4'
		 SELECT TOP 1 @ORAN4 = CONVERT(NUMERIC(20,2),CASE WHEN ISNULL(REPLACE(STRINGDEGER,',','.'),'0') = '' THEN 0 
					ELSE ISNULL(REPLACE(STRINGDEGER,',','.'),'0') END) FROM AYARLAR WHERE KULLANICI = 'GENEL' AND COMPADI = 'kdv5'


		set @ORAN1 = isnull(@ORAN1,0)
		set @ORAN2 = isnull(@ORAN2,0)
		set @ORAN3 = isnull(@ORAN3,0)
		set @ORAN4 = isnull(@ORAN4,0)

declare @SIPNOLARITABLE TABLE(P_ID VARCHAR(80),SIPNOLARI VARCHAR(500),
SIPTARIHLERI VARCHAR(500),SIPNO_TAR VARCHAR(1000))

INSERT INTO @SIPNOLARITABLE
SELECT P_ID,SUBSTRING(MAX(coalesce(''+' - ','')+SIPEVRAKNO),4,500),
SUBSTRING(max(COALESCE(''+' - ' , '' ) + RIGHT('0'+CAST(DAY(SIPTARIH) AS VARCHAR(2)),2)+'.'+
		CASE 
		  WHEN LEN(CAST(MONTH(SIPTARIH) AS VARCHAR(2)))>1 THEN CAST(MONTH(SIPTARIH) AS VARCHAR(2))
		  ELSE '0'+CAST(MONTH(SIPTARIH) AS VARCHAR(2)) END+'.'+CAST(YEAR(SIPTARIH) AS VARCHAR(4))),4,500),
SUBSTRING(max(COALESCE(''+' - ' , '' ) + SIPEVRAKNO+ ' / '+ RIGHT('0'+CAST(DAY(SIPTARIH) AS VARCHAR(2)),2)+'.'+
		CASE 
		  WHEN LEN(CAST(MONTH(SIPTARIH) AS VARCHAR(2)))>1 THEN CAST(MONTH(SIPTARIH) AS VARCHAR(2))
		  ELSE '0'+CAST(MONTH(SIPTARIH) AS VARCHAR(2)) END+'.'+CAST(YEAR(SIPTARIH) AS VARCHAR(4))),4,1000)
		   FROM FATURA_ALT
where isnull(SIPPID collate TURKISH_CI_AS,'')<>''
GROUP BY FATURA_ALT.P_ID


declare @IRSNOLARITABLE TABLE(P_ID VARCHAR(80),IRSNOLARI VARCHAR(500),
IRSTARIHLERI VARCHAR(500),IRSNO_TAR VARCHAR(1000))

INSERT INTO @IRSNOLARITABLE
SELECT FATURA_ALT.P_ID,SUBSTRING(MAX(coalesce(''+' - ','')+IRSEVRAKNO),4,500),
SUBSTRING(max(COALESCE(''+' - ' , '' ) + RIGHT('0'+CAST(DAY(IRSTARIH) AS VARCHAR(2)),2)+'.'+
		CASE 
		  WHEN LEN(CAST(MONTH(IRSTARIH) AS VARCHAR(2)))>1 THEN CAST(MONTH(IRSTARIH) AS VARCHAR(2))
		  ELSE '0'+CAST(MONTH(IRSTARIH) AS VARCHAR(2)) END+'.'+CAST(YEAR(IRSTARIH) AS VARCHAR(4))),4,500),
SUBSTRING(max(COALESCE(''+' - ' , '' ) + IRSEVRAKNO+ ' / '+ RIGHT('0'+CAST(DAY(IRSTARIH) AS VARCHAR(2)),2)+'.'+
		CASE 
		  WHEN LEN(CAST(MONTH(IRSTARIH) AS VARCHAR(2)))>1 THEN CAST(MONTH(IRSTARIH) AS VARCHAR(2))
		  ELSE '0'+CAST(MONTH(IRSTARIH) AS VARCHAR(2)) END+'.'+CAST(YEAR(IRSTARIH) AS VARCHAR(4))),4,1000)
		   FROM FATURA_ALT

where isnull(IRSPID collate TURKISH_CI_AS,'')<>''
GROUP BY FATURA_ALT.P_ID


delete FR_L1 where MP_ID = @mdl

INSERT INTO FR_L1 ( MP_ID,SIRANO,SUBE,EVRAKTAR,SAAT, TUR, AORS, ISLEMTIPI, EVRAKNO, OZELKOD1, OZELKOD2,
SATICI, DOVIZC, UGDK, IPTAL, KAPORAC,KULLANICI, KDVDH, TURAC,CARIADI ,DEPOREF , CARIREF, KASAKODU,VADETARIHI, 
YIORYD ,MASRAFMERKEZI, KAMPKODU, CARISUBE ,ADRESI, SEMT,SEHIR , VERGINO,VERGIDAIRESI, CRK , GK, TARIH_1, 
TARIH_2 ,AKTA_KULLANICI, ADRES1,SEHIR1 , SEMT1 , ADRESTIPI ,SEVKCARIREF , ISEMRIREF , ISEMRINO ,ULKE , 
ULKE1 , P_ID , BANKAREF , BANKAADI ,BANKAKODU , KASAKODUKULLAN , SILINDI ,CARIDVZCINSI , CARIDVZTUTAR , 
CARIDVZUGDK ,ULKEKODU , MASRAFY , MASRAFTL , MASRAFD ,EKMALIYETVAR , CARIP_ID , INT_1 ,ACIKLAMA ,
KASAP_ID , BANKAP_ID ,P5VS , YAZDIRILDI , IHRAKIYE ,TUTARTL , KDV1T , KDV2T ,KDV3T , KDV4T , OTVT ,
INDIRIMTL , MFIND ,TOPLAMTVKTL ,TEVKKDVDVZ ,TOPLAMD , TOPLAMTL , TUTARD ,OTVD , INDIRIMD , GENELTOPLAM , 
GENELTOPLAMD , TOPLAMKDV , TOPLAMKDVD ,TOPLAMOTV , TOPLAMOTVD , TOPLAMMASRAF , TOPLAMMASRAFD ,INDD ,
TOPLAMINDD ,TOPLAMGV , TOPLAMGVD , TOPLAMFON , TOPLAMFOND ,TOPLAMBAGKUR ,TOPLAMBAGKURD , TOPLAMKESINTI , 
TOPLAMKESINTID ,NETTOPLAM ,NETTOPLAMD ,TOPLAMOTVODENEN ,TOPLAMOTVODENEND , TOPLAMOTVTECIL , TOPLAMOTVTECILD , 
TOPLAMBORSA ,TOPLAMBORSAD , TOPLAMINDSIZKDV , TOPLAMINDTL ,TOPLAMIND , MATRAH1 , MATRAH2 , MATRAH3 , MATRAH4 ,
ORAN1  ,ORAN2 ,ORAN3 ,ORAN4 ,TOPLAMOIV ,TOPLAMOIVD ,TOPLAMMERAFONU ,TOPLAMMERAFONUD ,Yaziylatl,yaziyladvz_tr,
yaziyladvz_en ,IRSTARIHLERI,IRSNOLARI ,SIPTARIHLERI, SIPNOLARI,IRSNO_TAR, SIPNO_TAR,IRSNO ,IRSTAR ,IRSNOTARIH ,
ICARIP_ID ,ARATOPLAMTL ,ARATOPLAMD ,ODENECEKKDV ,Carimuhkodu ,Carivergino , CariVergiDairesi, Cariozelkod1 ,ACIKLAMA_1,
KDVTVK ,TOPLAMTVK ,KDVSIZTOPLAMTL ,GIBEVRAKNO , DURUMKODU , OKCFISI, TOPLAMRUSUM )

SELECT @mdl, SIRANO,	FATURA.SUBE,EVRAKTAR,FATURA.SAAT, FATURA.TUR, AORS, ISLEMTIPI, case when isnull(GIBEVRAKNO,'')<>'' then GIBEVRAKNO else EVRAKNO end EVRAKNO, OZELKOD1, FATURA.OZELKOD2,
SATICI, FATURA.DOVIZC, FATURA.UGDK, IPTAL, KAPORAC, FATURA.KULLANICI, FATURA.KDVDH, TURAC, 
		case 
	  when ISNULL(FATURA.CARIADI,'')<>'' AND ISNULL(FATURA.P5VS,0)=1 THEN FATURA.CARIADI
	  WHEN ISNULL(FATURA.TUR,0) IN (67,68) THEN FATURA.CARIADI	
	  else CARIGEN.STA end as CARIADI, DEPOREF, CARIREF, KASAKODU, VADETARIHI, 
YIORYD, FATURA.MASRAFMERKEZI, KAMPKODU, CARISUBE, ADRESI, FATURA.SEMT, FATURA.SEHIR, FATURA.VERGINO, VERGIDAIRESI, CARIGEN.CRK, GK, FATURA.TARIH_1, 
FATURA.TARIH_2,FATURA.AKTA_KULLANICI, FATURA.ADRES1, SEHIR1, SEMT1,ADRESTIPI, SEVKCARIREF, ISEMRIREF, ISEMRINO,FATURA.ULKE, 
ULKE1, FATURA.P_ID, BANKAREF, BANKAADI, BANKAKODU,KASAKODUKULLAN, SILINDI,CARIDVZCINSI, CARIDVZTUTAR, 
CARIDVZUGDK, FATURA.ULKEKODU, MASRAFY, MASRAFTL, MASRAFD,EKMALIYETVAR, CARIP_ID, FATURA.INT_1,left(EVTOP.ACIKLAMA,1000),
KASAP_ID, BANKAP_ID, P5VS, YAZDIRILDI, IHRAKIYE, 
	CASE WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMTL
	     WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMTL
	END AS TUTARTL, 
	
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
	   (KDV1TOP.TUTARTL - (KDV1TOP.INDTL+KDV1TOP.SATINDTL)+KDV1TOP.OTVTL)/100*@ORAN1
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   (KDV1TOP.TUTARTL - (KDV1TOP.INDTL+KDV1TOP.SATINDTL))/100*@ORAN1
	 WHEN FATURA.KDVDH = 1 THEN
	  ((KDV1TOP.TUTARTL / (1+(@ORAN1/100)))/100)*@ORAN1
	END AS KDV1T, 
	
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
	   (KDV2TOP.TUTARTL - (KDV2TOP.INDTL+KDV2TOP.SATINDTL)+KDV2TOP.OTVTL)/100*@ORAN2
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   (KDV2TOP.TUTARTL - (KDV2TOP.INDTL+KDV2TOP.SATINDTL))/100*@ORAN2
	 WHEN FATURA.KDVDH = 1 THEN
	  ((KDV2TOP.TUTARTL / (1+(@ORAN2/100)))/100)*@ORAN2
	END AS KDV2T,
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
	   (KDV3TOP.TUTARTL - (KDV3TOP.INDTL+KDV3TOP.SATINDTL)+KDV3TOP.OTVTL)/100*@ORAN3+RUSUM_TUTAR
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   (KDV3TOP.TUTARTL - (KDV3TOP.INDTL+KDV3TOP.SATINDTL))/100*@ORAN3+RUSUM_TUTAR
	 WHEN FATURA.KDVDH = 1 THEN
	  ((KDV3TOP.TUTARTL / (1+(@ORAN3/100)))/100)*@ORAN3+RUSUM_TUTAR
	END AS KDV3T, 
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
	   (KDV4TOP.TUTARTL - (KDV4TOP.INDTL+KDV4TOP.SATINDTL)+KDV4TOP.OTVTL)/100*@ORAN4
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   (KDV4TOP.TUTARTL - (KDV4TOP.INDTL+KDV4TOP.SATINDTL))/100*@ORAN4
	 WHEN FATURA.KDVDH = 1 THEN
	  ((KDV4TOP.TUTARTL / (1+(@ORAN4/100)))/100)*@ORAN4
	END AS KDV4T,	

	FTOP.TOPLAMOTV,
	FTOP.TOPLAMINDTL, 
	FATURA.MFIND,
	FTOP.TOPLAMTVK,
	FTOP.TOPLAMTVKD, 
	CASE 
	  WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMD
	  WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMD
	END AS TOPLAMD, 
	CASE 
	  WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMTL
	  WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMTL
	END AS TOPLAMTL, 
	CASE 
	  WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMD
	  WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMD
	END AS TUTARD, 
	FATURA.OTVD, 
	FATURA.INDIRIMD, 
	FATURA.GENELTOPLAM, 
	FATURA.GENELTOPLAMD, 
	FATURA.TOPLAMKDV, 
	FATURA.TOPLAMKDVD,
	FTOP.TOPLAMOTV,
	FTOP.TOPLAMOTVD, 
	FTOP.TOPLAMMASRAF, 
	FTOP.TOPLAMMASRAFD,
	FTOP.TOPLAMIND, 
	CASE 
		WHEN ISNULL(FATURA.UGDK,0)>0 THEN FTOP.TOPLAMIND/FATURA.UGDK 
		ELSE 0 END TOPLAMINDD,
	FTOP.TOPLAMGV, 
	FTOP.TOPLAMGVD, 
	FTOP.TOPLAMFON, 
	FTOP.TOPLAMFOND,
	FTOP.TOPLAMBAGKUR,
	FTOP.TOPLAMBAGKURD, 
	FTOP.TOPLAMKESINTI, 
	FTOP.TOPLAMKESINTID, 
	CASE 
	  WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMTL - (FTOP.TOPLAMIND + FTOP.TOPLAMKESINTI) 
	  WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMTL - (FTOP.TOPLAMIND + FTOP.TOPLAMKESINTI)
	END AS NETTOPLAM,
	CASE 
	  WHEN ISNULL(FATURA.KDVDH,0)=0 THEN FTOP.TOPLAMD - (FTOP.TOPLAMINDD + FTOP.TOPLAMKESINTID) 
	  WHEN ISNULL(FATURA.KDVDH,0)=1 THEN FTOP.DAHILTOPLAMD - (FTOP.TOPLAMINDD + FTOP.TOPLAMKESINTID)
	END AS NETTOPLAMD,
	FTOP.TOPLAMOTVODENEN,
	FTOP.TOPLAMOTVODENEND, 
	FTOP.TOPLAMOTVTECIL, 
	FTOP.TOPLAMOTVTECILD, 
	FTOP.TOPLAMBORSA,	
	FTOP.TOPLAMBORSAD, 
	FTOP.TOPLAMINDSIZKDV, 
	FTOP.TOPLAMINDTL,
	FTOP.TOPLAMIND, 
	
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
		KDV1TOP.TUTARTL - (KDV1TOP.INDTL+KDV1TOP.SATINDTL)+KDV1TOP.OTVTL	
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   KDV1TOP.TUTARTL - (KDV1TOP.INDTL+KDV1TOP.SATINDTL)
	 WHEN FATURA.KDVDH = 1 THEN
	   KDV1TOP.TUTARTL/(1+(@ORAN1/100))
	END AS MATRAH1, 
	
	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
		KDV2TOP.TUTARTL - (KDV2TOP.INDTL+KDV2TOP.SATINDTL)+KDV2TOP.OTVTL	
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   KDV2TOP.TUTARTL - (KDV2TOP.INDTL+KDV2TOP.SATINDTL)
	 WHEN FATURA.KDVDH = 1 THEN
	   KDV2TOP.TUTARTL/(1+(@ORAN2/100))
	END AS MATRAH2, 

	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
		KDV3TOP.TUTARTL - (KDV3TOP.INDTL+KDV3TOP.SATINDTL)+KDV3TOP.OTVTL	
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   KDV3TOP.TUTARTL - (KDV3TOP.INDTL+KDV3TOP.SATINDTL)
	 WHEN FATURA.KDVDH = 1 THEN
	   KDV3TOP.TUTARTL/(1+(@ORAN3/100))
	END AS MATRAH3, 

	CASE
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=0 THEN
		KDV4TOP.TUTARTL - (KDV4TOP.INDTL+KDV4TOP.SATINDTL)+KDV4TOP.OTVTL	
	 WHEN FATURA.KDVDH = 0 AND ISNULL(IHRAKIYE,0)=1 THEN
	   KDV4TOP.TUTARTL - (KDV4TOP.INDTL+KDV4TOP.SATINDTL)
	 WHEN FATURA.KDVDH = 1 THEN
	   KDV4TOP.TUTARTL/(1+(@ORAN4/100))
	END AS MATRAH4, 
	
	ORAN1=@ORAN1 ,ORAN2=@ORAN2,ORAN3=@ORAN3,ORAN4= @ORAN4,
	FTOP.TOPLAMOIV,
	FTOP.TOPLAMOIVD, 
	FTOP.TOPLAMMERAFONU,
	FTOP.TOPLAMMERAFONUD,
	
	left([zirvegenel].dbo.paraOku(round(FATURA.GENELTOPLAM,2),1,0),250) AS YAZIYLATL,
	left([zirvegenel].dbo.ParaOku(round(FATURA.GENELTOPLAMD,4),FATURA.DOVIZC,0),250) YAZIYLADVZ_TR,
	left([zirvegenel].dbo.ParaOku_Eng(round(FATURA.GENELTOPLAMD,4),FATURA.DOVIZC,0),250) YAZIYLADVZ_EN,

    '', --IRSTAB.IRSTARIHLERI, 
	'', --IRSTAB.IRSNOLARI,
    '', --SIPTAB.SIPTARIHLERI, 
	'', --SIPTAB.SIPNOLARI,
	'', --IRSTAB.IRSNO_TAR, 
	'', --SIPTAB.SIPNO_TAR,
	IRSNO,IRSTAR,
	IRSNO+' '+CAST(IRSTAR AS VARCHAR(10)) AS IRSNOTARIH,
	ISNULL(EVTOP.ICARIPID,'') AS ICARIP_ID,
	ARATOPLAMTL=
             		Round(ISNULL(FATURA.GENELTOPLAM,0)-ISNULL(FATURA.TOPLAMKDV,0)-ISNULL(RUSUM_TUTAR,0)+CASE WHEN ISNULL(FTOP.TOPLAMTVK,0) > 0 THEN ISNULL(FTOP.TOPLAMTVK,0) ELSE 0 END,2),
	ARATOPLAMD= 
		ISNULL(FATURA.GENELTOPLAMD,0)-ISNULL(FATURA.TOPLAMKDVD,0)+CASE WHEN ISNULL(FTOP.TOPLAMTVKD,0) > 0 THEN ISNULL(FTOP.TOPLAMTVKD,0) ELSE 0 END,

	ODENECEKKDV= ISNULL(FATURA.TOPLAMKDV,0)-ISNULL(FTOP.TOPLAMTVK,0),
	Carimuhkodu = CARIGEN.GMHK,
	Carivergino=CARIGEN.VERGINO,
	CariVergiDairesi=CARIGEN.VERGID,
	Cariozelkod1 = CARIGEN.OZELKOD,
	EVTOP.ACIKLAMA AS ACIKLAMA_1,
	KDVTVK=
	    Round(FATURA.TOPLAMKDV-CASE WHEN FATURA.TUR=60 THEN Round(FTOP.TOPLAMTVK,2) ELSE 0 END,2),
	TOPLAMTVK=FTOP.TOPLAMTVK,
  CASE WHEN ISNULL(FATURA.KDVDH,0) = 0 THEN FTOP.TUTARTL
	   WHEN ISNULL(FATURA.KDVDH,0) = 1 THEN FATURA.GENELTOPLAM - FATURA.TOPLAMKDV + FTOP.TOPLAMINDTL
   END as KDVSIZTOPLAMTL,
  FATURA.GIBEVRAKNO, FATURA.DURUMKODU, ISNULL(OKCFISI,0),ISNULL(FTOP.RUSUM_TUTAR,0)
FROM FATURA
LEFT JOIN @FATURATOPLAMLARI AS FTOP ON FTOP.FP_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS
LEFT JOIN @IRSNOLARITABLE AS IRSTAB ON IRSTAB.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS
LEFT JOIN @SIPNOLARITABLE AS SIPTAB ON SIPTAB.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS
LEFT JOIN @KDVTOPLAMLARI AS KDV1TOP ON KDV1TOP.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS AND KDV1TOP.KDVY = @ORAN1
LEFT JOIN @KDVTOPLAMLARI AS KDV2TOP ON KDV2TOP.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS AND KDV2TOP.KDVY = @ORAN2
LEFT JOIN @KDVTOPLAMLARI AS KDV3TOP ON KDV3TOP.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS AND KDV3TOP.KDVY = @ORAN3
LEFT JOIN @KDVTOPLAMLARI AS KDV4TOP ON KDV4TOP.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS AND KDV4TOP.KDVY = @ORAN4
LEFT JOIN (SELECT P_ID,MAX(ACIKLAMA) AS ACIKLAMA,MAX(ICARIPID) AS ICARIPID FROM EVRAKTOPLAMLARI GROUP BY P_ID) AS EVTOP ON EVTOP.P_ID collate TURKISH_CI_AS = FATURA.P_ID collate TURKISH_CI_AS
LEFT JOIN CARIGEN ON CARIGEN.P_ID collate TURKISH_CI_AS = FATURA.CARIP_ID collate TURKISH_CI_AS
WHERE EVRAKTAR BETWEEN @TARIH1 AND @TARIH2
--<FATFLT>




 AND ((EVRAKTAR>='01.06.2022') and (EVRAKTAR<='29.06.2022')) and (FATURA.TUR IN (60,63,67,65,280,281)) and ((IPTAL IS NULL) OR (IPTAL = 0)) AND CARIP_ID IN (SELECT P_ID FROM CARIGEN WHERE (CRK>='120.0010067299') and (CRK<='336.10.002'))

select *,  (Select Dovizcinsi from [zirvegenel].dbo.dovizcin WHERE Kod = FR_L1.DOVIZC) As DovizCinsi from FR_L1 where MP_ID = @mdl
ORDER BY EVRAKTAR,AORS,TUR,CASE WHEN ISNULL(GIBEVRAKNO,'')='' then EVRAKNO ELSE GIBEVRAKNO END


