SELECT   TURAC AS FaturaTuru,MONTH(EVRAKTAR) AS Ay,SUM(GENELTOPLAM) AS GenelToplam,COUNT(GENELTOPLAM) AS EvrakSayisi--,SUM(TOPLAMKDV) AS TOPLAMKDV
		FROM FATURA
		LEFT JOIN (SELECT FATURA_ALT.P_ID,SUM(ISNULL(TUTARTL,0)) TUTARTL2, SUM(ISNULL(TUTARTL,0)) TUTARTL,SUM(ISNULL(TUTARD,0)) TUTARD,	
		SUM(ISNULL(OTVTL,0)) OTVTL, SUM(ISNULL(TEVKTL,0)) TEVKTL ,SUM(ISNULL(TEVKD,0)) TEVKD, 
		SUM(ISNULL(GVSTOPAJTUTARITL,0)) GVSTOPAJTUTARITL,SUM(ISNULL(FONTUTARITL,0)) FONTUTARITL,SUM(ISNULL(BAGKURTUTARTL,0)) BAGKURTUTARTL,
		SUM(ISNULL(KESINTITOPLAMTL,0)) KESINTITOPLAMTL,SUM(ISNULL(SOTVODENENTL,0)) SOTVODENENTL,SUM(ISNULL(SOTVTECILTL,0)) SOTVTECILTL,SUM(ISNULL(BORSATUTARTL,0)) BORSATUTARTL,
		SUM(ISNULL(INDSIZKDV,0)) INDSIZKDV,SUM(ISNULL(INDTL,0)) INDTL, SUM(ISNULL(OIVTUTARTL,0)) OIVTUTARTL,
		SUM(ISNULL(MFYTUTARTL,0)) MFYTUTARTL,
		SUM(isnull(TMT,0)) TMT,			   
		SUM(isnull(DMT,0)) DMT,
		SUM(ISNULL(SATMASRAFTL,0)) SATMASRAFTL, SUM(ISNULL(NETTUTARTL,0)) NETTUTARTL, SUM(ISNULL(INDD,0)) INDD,
		SUM(isnull(RUSUM_TUTAR,0)) RUSUM_TUTAR
		FROM FATURA_ALT GROUP BY FATURA_ALT.P_ID) AS TBL_FATURA_ALT ON TBL_FATURA_ALT.P_ID  =      FATURA.P_ID
		LEFT JOIN CARIGEN ON CARIGEN.P_ID collate TURKISH_CI_AS = FATURA.CARIP_ID collate TURKISH_CI_AS
		GROUP BY TURAC,MONTH(EVRAKTAR)
		ORDER BY MONTH(EVRAKTAR)
		


SELECT   TURAC AS FaturaTuru,MONTH(EVRAKTAR) AS Ay,DAY(EVRAKTAR) AS Gun, FORMAT( SUM(GENELTOPLAM),'N') AS GenelToplam,COUNT(GENELTOPLAM) AS EvrakSayisi--,SUM(TOPLAMKDV) AS TOPLAMKDV
		FROM FATURA
		LEFT JOIN (SELECT FATURA_ALT.P_ID,SUM(ISNULL(TUTARTL,0)) TUTARTL2, SUM(ISNULL(TUTARTL,0)) TUTARTL,SUM(ISNULL(TUTARD,0)) TUTARD,	
		SUM(ISNULL(OTVTL,0)) OTVTL, SUM(ISNULL(TEVKTL,0)) TEVKTL ,SUM(ISNULL(TEVKD,0)) TEVKD, 
		SUM(ISNULL(GVSTOPAJTUTARITL,0)) GVSTOPAJTUTARITL,SUM(ISNULL(FONTUTARITL,0)) FONTUTARITL,SUM(ISNULL(BAGKURTUTARTL,0)) BAGKURTUTARTL,
		SUM(ISNULL(KESINTITOPLAMTL,0)) KESINTITOPLAMTL,SUM(ISNULL(SOTVODENENTL,0)) SOTVODENENTL,SUM(ISNULL(SOTVTECILTL,0)) SOTVTECILTL,SUM(ISNULL(BORSATUTARTL,0)) BORSATUTARTL,
		SUM(ISNULL(INDSIZKDV,0)) INDSIZKDV,SUM(ISNULL(INDTL,0)) INDTL, SUM(ISNULL(OIVTUTARTL,0)) OIVTUTARTL,
		SUM(ISNULL(MFYTUTARTL,0)) MFYTUTARTL,
		SUM(isnull(TMT,0)) TMT,			   
		SUM(isnull(DMT,0)) DMT,
		SUM(ISNULL(SATMASRAFTL,0)) SATMASRAFTL, SUM(ISNULL(NETTUTARTL,0)) NETTUTARTL, SUM(ISNULL(INDD,0)) INDD,
		SUM(isnull(RUSUM_TUTAR,0)) RUSUM_TUTAR
		FROM FATURA_ALT GROUP BY FATURA_ALT.P_ID) AS TBL_FATURA_ALT ON TBL_FATURA_ALT.P_ID  =      FATURA.P_ID
		LEFT JOIN CARIGEN ON CARIGEN.P_ID collate TURKISH_CI_AS = FATURA.CARIP_ID collate TURKISH_CI_AS
		GROUP BY TURAC,MONTH(EVRAKTAR),DAY(EVRAKTAR)
		ORDER BY MONTH(EVRAKTAR),DAY(EVRAKTAR)
		