SELECT TBL.BAKIYE, SIRANO,SUBE,EVRAKTAR,SAAT,TUR,AORS,ISLEMTIPI,EVRAKNO,OZELKOD1,OZELKOD2,SATICI,DOVIZC,UGDK,KAPORAC,KDVDH,TURAC,CARIADI,CRK
--CASE WHEN TURAC = ''
GENELTOPLAM,CARIADI FROM 
  (SELECT  CRK AS   CARIKODU,CAST(  abs( ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2))   AS VARCHAR(20)) +  ' (' +
CASE WHEN  ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2)>0 THEN 'B' WHEN  ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2)< 0 THEN 'A' ELSE ' ' END + ')'  AS BAKIYE   
  FROM CARIT_ISLEM_TUTAR()  
   left join CARIGEN on CARIP_ID=P_ID  where CRK is not null 
GROUP BY CRK 
) TBL  

left join [LISTEFATURA]() t1  ON TBL.CARIKODU = t1.GMHK
WHERE TURAC LIKE 'sati%'


SELECT TBL.BAKIYE,  

CASE WHEN TURAC = 'Satýþ Ýade Faturasý' or TURAC = 'Gider Faturasý' then KDVDH * -1 else KDVDH end as KDVDH,
CASE WHEN TURAC = 'Satýþ Ýade Faturasý' or TURAC = 'Gider Faturasý' then GENELTOPLAM * -1 else GENELTOPLAM end as GENELTOPLAM,
CASE WHEN TURAC = 'Satýþ Ýade Faturasý' or TURAC = 'Gider Faturasý' then TUTARTL * -1 else TUTARTL end as TUTARTL,
TBL.BAKIYE, SIRANO,SUBE,EVRAKTAR,SAAT,TUR,AORS,ISLEMTIPI,EVRAKNO,OZELKOD1,OZELKOD2,SATICI,DOVIZC,UGDK,KAPORAC,TURAC,CARIADI,CRK,* FROM
  (SELECT  CRK AS   CARIKODU,FORMAT(  abs( ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2)) ,'N') +  ' (' +
CASE WHEN  ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2)>0 THEN 'B' WHEN  ROUND(Round(SUM(TUTARB),6) -  Round(SUM(TUTARA),6),2)< 0 THEN 'A' ELSE ' ' END + ')'  AS BAKIYE  
  FROM CARIT_ISLEM_TUTAR() 
   left join CARIGEN on CARIP_ID=P_ID  where CRK is not null
GROUP BY CRK
) TBL
left join [LISTEFATURA]() t1  ON TBL.CARIKODU = t1.GMHK
WHERE T1.Iptal = 0  