USE [zirvegenel]
GO

/****** Object:  View [dbo].[VW_CekBordroListesi_2025]    Script Date: 13.01.2025 09:57:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


 CREATE view [dbo].[VW_CekBordroListesi_2025] as 
select top 10000000 --BRDTUR,
FORMAT (DDTARIHI, 'dd-MM-yyyy') as BORDROTARIHISTR,
FORMAT (vade, 'dd-MM-yyyy') as VADESTR,
BORDRONOS_S AS BORDRONOBANKA,DDTARIHI AS BORDROTARIHI, BANKGEN.BANKAADI AS TEMINATBANKA, 
CASE WHEN BRDTUR = '103' THEN 'Ç-S Çýkýþý (Banka Teminata)' 
WHEN BRDTUR = '100' THEN 'Çek-Senet Giriþi' 
WHEN BRDTUR = '107' THEN 'Ç-S Giriþi (Ýade Banka)' 
else 'Diðer' end as ÇekSenetTuru,

BORDROCEKLER.*,SONBCEKLER.DURUMX from 
[TUÐRAL_DÖKÜM_LTD_2025T].. BORDROCEKLER BORDROCEKLER
LEFT JOIN [TUÐRAL_DÖKÜM_LTD_2025T]..BANKGEN ON BORDROCEKLER.BRDBANKAREFNO = BANKGEN.BANKAREFNO
LEFT OUTER JOIN (SELECT     CEK_PID, P_ID, MAX(DURUM) AS DURUMX FROM [TUÐRAL_DÖKÜM_LTD_2025T]..BORDROCEKLER AS SCEK WHERE 
(CSSATIRREF = ISNULL ((SELECT     MAX(CSSATIRREF) AS Expr1 FROM [TUÐRAL_DÖKÜM_LTD_2025T]..BORDROCEKLER AS SSC

WHERE (CEK_PID = SCEK.CEK_PID)), 0))
GROUP BY CEK_PID, P_ID) AS SONBCEKLER ON SONBCEKLER.CEK_PID = BORDROCEKLER.CEK_PID    --WHERE BORDRONOS_S = '119'--BORDROCEKLER.P_ID = '594z05d6-814e-4ra3-b04e-av137de926da' Order by Vade
--select * from BORDROCEKLER  where P_ID = '594z05d6-814e-4ra3-b04e-av137de926da'

GO


