USE [zirvegenel]
GO

/****** Object:  View [dbo].[VW_Son3AyFaturaKesilenCariler_25]    Script Date: 13.01.2025 09:58:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_Son3AyFaturaKesilenCariler_25] as 
WITH Son3AyFatura AS (
    SELECT   CARIADI
    FROM VW_FaturaListesi_25
    WHERE EVRAKTAR >= DATEADD(MONTH, -3, GETDATE())
	GROUP BY CARIADI
)

SELECT CARIGEN.CRK,CARIGEN.STA, CARIGEN.VERGINO, CARIGEN.TEL, CARIGEN.EPOSTA
FROM [TUÐRAL_DÖKÜM_LTD_2025T]..CARIGEN CARIGEN
LEFT JOIN Son3AyFatura F ON CARIGEN.STA = F.CARIADI
WHERE F.CARIADI IS NOT NULL
AND SUBSTRING(CARIGEN.CRK, 1, 3) = '120';
GO


