USE [zirvegenel]
GO

/****** Object:  View [dbo].[VW_FaturaListesi_25]    Script Date: 13.01.2025 09:58:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE view [dbo].[VW_FaturaListesi_25] as 
SELECT DISTINCT
    YEAR(EF.EVRAKTAR) AS YIL,
    MONTH(EF.EVRAKTAR) AS AY,
	DAY(EF.EVRAKTAR) AS GUN,
    EF.P_ID,
    EF.EVRAKTAR,
    EF.EVRAKNO,
    EF.TURAC,
    EF.CARIADI,
    EF.GENELTOPLAM,
	 
    ES.STK,
    ES.STA,
    ES.STB,
    ES.MIKTAR,
    ES.BRFTL,
    ES.TEVKORANI,
    ES.TUTARTL,
    ES.KDVTL,
	ES.TUTARTL +     ES.KDVTL AS SATIRTOPLAMI 
	 ,vw_CariBakiye_2025.BAKIYE
FROM 
 [TUÐRAL_DÖKÜM_LTD_2025T]. dbo.[EFATURA_LISTESI]() EF
CROSS APPLY 
    [TUÐRAL_DÖKÜM_LTD_2025T]. [dbo].[EFATURA_SATIR](EF.P_ID, 1) ES
LEFT JOIN vw_CariBakiye_2025   ON vw_CariBakiye_2025.P_ID = EF.CARIP_ID

UNION ALL


SELECT DISTINCT
    YEAR(EF.EVRAKTAR) AS YIL,
    MONTH(EF.EVRAKTAR) AS AY,
	DAY(EF.EVRAKTAR) AS GUN,
    EF.P_ID,
    EF.EVRAKTAR,
    EF.EVRAKNO,
    EF.TURAC,
    EF.CARIADI,
    EF.GENELTOPLAM,
	 
    ES.STK,
    ES.STA,
    ES.STB,
    ES.MIKTAR,
    ES.BRFTL,
    ES.TEVKORANI,
    ES.TUTARTL,
    ES.KDVTL,
	ES.TUTARTL +     ES.KDVTL AS SATIRTOPLAMI 
	 ,vw_CariBakiye_2025.BAKIYE
FROM 
[TUÐRAL_DÖKÜM_LTD_2025T].dbo.EARSIVLIST_FUNC('20250101','20251231') 
EF
CROSS APPLY 
    [TUÐRAL_DÖKÜM_LTD_2025T]. [dbo].[EFATURA_SATIR](EF.P_ID, 1) ES
LEFT JOIN vw_CariBakiye_2025   ON vw_CariBakiye_2025.P_ID = EF.CARIP_ID

--WHERE EF.CARIADI LIKE 'HÝK%'
	--select * from  [TUÐRAL_DÖKÜM_LTD_2025T]. dbo.CARIDURUM()
	--select * from vw_CariBakiye_2025


--	 SELECT * FROM 
--[TUÐRAL_DÖKÜM_LTD_2025T]. dbo.EARSIVLIST_FUNC('20250101','20251231') 



GO


