ALTER DATABASE TUÐRAL_DÖKÜM_LTD_2021T SET SINGLE_USER;
 
DBCC CHECKDB (TUÐRAL_DÖKÜM_LTD_2021T,REPAIR_REBUILD) WITH NO_INFOMSGS,ALL_ERRORMSGS;
 
ALTER DATABASE TUÐRAL_DÖKÜM_LTD_2021T SET ONLINE;
 
ALTER DATABASE TUÐRAL_DÖKÜM_LTD_2021T SET MULTI_USER;