USE [zirvegenel]
GO

/****** Object:  View [dbo].[VW_CariBakiye_2022]    Script Date: 4.08.2022 09:48:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--select * from [VW_CariBakiye_2022] where OZELKOD2 like 'sa%'
 ALTER view [dbo].[VW_CariBakiye_2022] as 
Select   top 1000000 CARI_REF=Max(REF), CARIGEN.CRK AS CARIKODU,CARIGEN.STA AS CARIADI, BAKIYE=ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)  
,CASE WHEN ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)<0 THEN 'A' 
      WHEN ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)>0 THEN 'B' 
	  ELSE '' END AS BAKIYETURU, CARIGEN.OZELKOD2 
	  ,ODEMESURESI
from [TUÐRAL_DÖKÜM_LTD_2022T]..CARIT_ISLEM_TUTAR_DVZ() left join [TUÐRAL_DÖKÜM_LTD_2022T]..CARIGEN on CARIP_ID=P_ID
  WHERE   LEN(CARIGEN.CRK )>3 and CARIGEN.STA LIKE '%%'
group by CARIP_ID,CARIGEN.CRK,CARIGEN.STA ,CARIGEN.OZELKOD2 ,ODEMESURESI
ORDER BY CRK
--SELECT * FROM [TUÐRAL_DÖKÜM_LTD_2022T]..CARIGEN WHERE LEN(OZELKOD) >1 'TAKÝP'


GO


