--select * from VW_Son3AyFaturaKesilmeyenCariler_24
--SELECT * FROM VW_Son3AyFaturaKesilenCariler_24

CREATE VIEW VW_Son3AyFaturaKesilenCariler_24 as 
WITH Son3AyFatura AS (
    SELECT   CARIADI
    FROM VW_FaturaListesi_24
    WHERE EVRAKTAR >= DATEADD(MONTH, -3, GETDATE())
	GROUP BY CARIADI
)

SELECT CARIGEN.CRK,CARIGEN.STA, CARIGEN.VERGINO, CARIGEN.TEL, CARIGEN.EPOSTA
FROM [TUÐRAL_DÖKÜM_LTD_2024T]..CARIGEN CARIGEN
LEFT JOIN Son3AyFatura F ON CARIGEN.STA = F.CARIADI
WHERE F.CARIADI IS NOT NULL
AND SUBSTRING(CARIGEN.CRK, 1, 3) = '120';