USE [TUÐRAL_DÖKÜM_LTD_2022T]
GO
/****** Object:  UserDefinedFunction [dbo].[CARI_EKSTRE]    Script Date: 11.03.2022 23:09:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--alter VIEW VW_CariHesapEkstresi as 
SELECT  CBKISLEMREF SATIRNO  
        ,TARIH AS FATURATARIHI
	    ,EVRAKNO  
		, ISLEMAC AS EVRAKTURU
		,ACIKLAMA
          -- UGDK, --ugdk = 0 ise alacak
		 
		
	--	,  CASE WHEN TUTARB>0 THEN TUTARB ELSE TUTARA END - FATURA_ALT.KDVTL     AS TUTAR
	   , TUTARB AS BORC   -- borç olacak
	   ,TUTARA AS ALACAK 
	   ,CariBakiyesi  
	   ,CASE WHEN TUTARB>0 THEN 'B' WHEN TUTARA>0 THEN 'A' END AS BA 
	   ,VADETARIHI
		 
	
		/*
		,CARIGEN.CRK AS CARINO
		,CARIGEN.STA AS CARIADI
		,CARIGEN.SEHIR
		,CARIGEN.VERGID
		,CARIGEN.VERGINO
		,0 ISYERINO
		,CARIGEN.SEMT AS ISYERIADI
		,0 BOLUMNO
		,CARIGEN.SEMT AS BOLUMADI
		,YEAR(TARIH) AS YIL
		,MONTH(TARIH) AS AY
		, CASE WHEN TUTARB>0 THEN TUTARB ELSE TUTARA END - FATURA_ALT.KDVTL  AS VERGIMATRAHI
		 
		,*
		--,FATURA_ALT.KDVY
		 */
		FROM CARI_EKSTRE('120.0430367835','20220101','20220301')
		LEFT JOIN (select 
		P_ID,KDVY=SUM(isnull(KDVY,0)),KDVTL=SUM(isnull(KDVTL,0)),TEVKTL=SUM(isnull(TEVKTL,0))   
		 
	from 
	FATURA_ALT GROUP BY P_ID) FATURA_ALT ON FATURA_ALT.P_ID = EVRAKP_ID
	   LEFT JOIN CARIGEN ON CARIGEN.P_ID = CARIP_ID
	 
	 

	 order by FATURATARIHI