Select CARI_REF=Max(REF), CARIGEN.CRK AS CARIKODU,CARIGEN.STA AS CARIADI, BAKIYE=ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)  
,CASE WHEN ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)<0 THEN 'A' 
      WHEN ROUND(Isnull(sum(TUTARB),0)-Isnull(sum(TUTARA),0),2)>0 THEN 'B' 
	  ELSE '' END AS BAKIYETURU
from CARIT_ISLEM_TUTAR_DVZ() left join CARIGEN on CARIP_ID=P_ID
  WHERE   LEN(CARIGEN.CRK )>3
group by CARIP_ID,CARIGEN.CRK,CARIGEN.STA 

ORDER BY CRK